export const AI_SUBPAGE_DATA: Record<string, any> = {
  "ai-video-ads": {
    "ai-meta-ads-production-india": {
      h1: "AI Meta Ads Production Company India",
      cat: "AI Video Ads",
      intro: "Define Perspective is the leading AI Meta ads production company in India, specializing in high-converting Facebook and Instagram video content. We leverage neural networks to create 'stopping power' ads that thrive in the Meta ecosystem, serving brands in Kerala, Kochi, Trivandrum, and the UAE.",
      services: ["AI Meta Hooks", "Dynamic IG Story Ads", "Neural FB Feed Videos", "Automated Ad Scaling"],
      benefits: ["Lower CPMs", "Higher CTR", "Infinite Ad Variations", "Meta-Algorithm Optimized"],
      locationBlock: "Dominating Meta advertising in India, Kerala, and the UAE from our tech nodes in Kochi and Trivandrum.",
      faqs: [{ q: "What are AI Meta ads?", a: "AI Meta ads are video commercials generated using neural networks specifically optimized for Facebook and Instagram's engagement algorithms." }, { q: "How fast can you scale Meta ads with AI?", a: "We can deploy 50+ variations in 48 hours to help you find the winning creative faster than traditional methods." }]
    },
    "ai-youtube-ads-production-company": {
      h1: "AI YouTube Ads Production Company India",
      cat: "AI Video Ads",
      intro: "Elite AI-powered YouTube ad production for brands in India and UAE. We engineer high-retention pre-roll and bumper ads using neural workflows in Kochi and Trivandrum.",
      services: ["AI Pre-roll Ads", "Bumper Ad Automation", "YouTube Hook Optimization", "Scaling YT Shorts Ads"],
      benefits: ["Maximized View-Through Rate", "Lower Cost Per Conversion", "Rapid Ad Variation Testing", "YouTube Algorithm Alignment"],
      locationBlock: "Delivering high-performance YouTube ads across India, Kerala, Kochi, and the UAE.",
      faqs: [{ q: "How does AI help in YouTube ads?", a: "AI optimizes the first 5 seconds of the ad to ensure maximum retention before the skip button appears." }]
    },
    "performance-ai-creatives-agency": {
      h1: "Performance AI Creatives Agency India",
      cat: "AI Video Ads",
      intro: "Data-driven performance AI creatives designed for massive scale. Serving the Indian and UAE markets with ROAS-focused video assets.",
      services: ["D2C Performance Videos", "High-ROAS Ad Creatives", "Neural Ad Assets", "Performance Scaling Loops"],
      benefits: ["3x Higher ROAS", "Dynamic Creative Volume", "Reduced Ad Fatigue", "Data-Validated Visuals"],
      locationBlock: "The primary performance AI creative hub in Kerala, serving Kochi, Trivandrum, and the UAE.",
      faqs: [{ q: "What are performance AI creatives?", a: "These are video assets generated by AI models trained on millions of high-converting ad data points." }]
    },
    "ai-ab-test-variations-production": {
      h1: "AI A/B Test Variations Production",
      cat: "AI Video Ads",
      intro: "Stop guessing. Use AI to generate infinite A/B test variations of your best performing video ads.",
      services: ["Visual Variant Generation", "Hook A/B Testing", "Neural Iteration Hub", "Background & Talent Swaps"],
      benefits: ["Faster Creative Winning", "Minimized Testing Budget", "Scientific Ad Scaling", "Hyper-Iterative Workflows"],
      locationBlock: "Leading AI ad iteration across India and the UAE from our Trivandrum and Kochi labs.",
      faqs: [{ q: "Can AI generate variations automatically?", a: "Yes, our systems can take one winning ad and generate 20+ unique variations by changing hooks and backgrounds." }]
    }
  },
  "ai-social-video": {
    "ai-instagram-reels-production-india": {
      h1: "AI Instagram Reels Production India",
      cat: "AI Social Video",
      intro: "Master the Gram with AI-generated reels that capture attention instantly. Serving Kochi, Kerala, and UAE brands.",
      services: ["Viral AI Reels", "Automated Reel Batching", "Neural Trend Syncing", "Elite Reel Mastery"],
      benefits: ["Higher Organic Reach", "Daily Posting Velocity", "Consistent Brand Aesthetic", "Algorithm-Gaming Visuals"],
      locationBlock: "The top AI Reels agency in Kerala, Kochi, and the UAE.",
      faqs: [{ q: "Is AI good for organic reels?", a: "Absolutely. AI helps in creating highly visually engaging content that triggers the Instagram explore algorithm." }]
    },
    "ai-youtube-shorts-production-agency": {
      h1: "AI YouTube Shorts Production Agency",
      cat: "AI Social Video",
      intro: "Dominate YouTube Shorts with neural video production optimized for rapid subscriber growth.",
      services: ["AI Shorts Batching", "Neural Hook Design", "YouTube Vertical Mastery", "Automated Captioning"],
      benefits: ["Rapid Channel Growth", "High-Volume Posting", "Consistent Quality", "Platform-Specific Hooks"],
      locationBlock: "Producing viral YouTube Shorts across India, Kerala, and the UAE.",
      faqs: [{ q: "Do AI Shorts rank well?", a: "Yes, they are indexed highly by both YouTube's algorithm and Google search." }]
    },
    "ai-tiktok-video-production-uae": {
      h1: "AI TikTok Video Production UAE",
      cat: "AI Social Video",
      intro: "Leading AI TikTok production in the UAE and India. Content built for high-retention and viral potential.",
      services: ["AI TikTok Batching", "Neural Trend Prediction", "UGC Style AI Ads", "TikTok Vertical Strategy"],
      benefits: ["Viral Loop Optimization", "High Engagement Rates", "Rapid Trend Response", "Automated Content Sourcing"],
      locationBlock: "Dominating TikTok in the UAE and India from our Kochi and Trivandrum hubs.",
      faqs: [{ q: "Can AI replicate TikTok trends?", a: "Yes, our AI monitors global trends and adapts your brand content in real-time." }]
    },
    "daily-ai-content-hub-india": {
      h1: "Daily AI Content Hub India",
      cat: "AI Social Video",
      intro: "Scale your social presence with daily AI-generated video content. Zero friction, maximum consistency.",
      services: ["30-Day Content Packs", "Automated Daily Reals", "Social Media Consistency Hub", "Neural News Jacking"],
      benefits: ["Unbeatable Consistency", "Lower Cost Per Post", "Total Brand Presence", "Zero Effort Production"],
      locationBlock: "Scaling social visibility daily across India, Kerala, and the UAE.",
      faqs: [{ q: "Can you really post daily with AI?", a: "Yes, our AI systems allow for a month's worth of content to be produced in one sitting." }]
    }
  },
  "ai-post-production": {
    "neural-ai-video-editing-services": {
        h1: "Neural AI Video Editing Services",
        cat: "AI Post-Production",
        intro: "Experience the future of post-production with neural-assisted video editing in India and UAE.",
        services: ["AI-Automated Cuts", "Neural Pacing Optimization", "Intelligent Storytelling", "Fast-Batch Editing"],
        benefits: ["80% Faster Delivery", "Perfect Visual Pacing", "Automated Footage Sorting", "Consistent Artistic Quality"],
        locationBlock: "Leading AI editing across Kochi, Kerala, and the UAE.",
        faqs: [{ q: "Does AI replace human editors?", a: "No, it enhances them by automating tedious tasks so they can focus on storytelling." }]
    },
    "ai-vfx-motion-graphics-india": {
        h1: "AI VFX & Motion Graphics India",
        cat: "AI Post-Production",
        intro: "High-end AI-generated visual effects and motion graphics for brands in Kerala and UAE.",
        services: ["AI Environment Cleanup", "Neural Object Removal", "Automated Motion Tracking", "AI Background Extension"],
        benefits: ["Reduced Set Costs", "Cinematic Visual Polish", "Rapid VFX Iteration", "Indistinguishable Quality"],
        locationBlock: "The top AI VFX house in Kochi and Trivandrum, serving the UAE.",
        faqs: [{ q: "Can AI clean up footage?", a: "Yes, AI can perfectly remove unwanted objects or wires from shots in seconds." }]
    },
    "ai-color-grading-services-kerala": {
        h1: "AI Color Grading Services Kerala",
        cat: "AI Post-Production",
        intro: "Professional AI-powered color grading and cinematic mastering in India and UAE.",
        services: ["Neural Color Matching", "AI Skin Tone Optimization", "Cinematic Look Generation", "Batch Look Consistency"],
        benefits: ["Cinematic Grade in Seconds", "Consistent Multi-Shot Look", "Industry-Standard Mastering", "Zero-Guesswork Grading"],
        locationBlock: "Expert AI colorists in Kochi and Trivandrum, serving global markets.",
        faqs: [{ q: "Is AI color grading accurate?", a: "Yes, it uses reference frames to match colors across entire projects perfectly." }]
    },
    "ai-video-enhancement-hub-india": {
        h1: "AI Video Enhancement Hub India",
        cat: "AI Post-Production",
        intro: "Upscale and enhance low-resolution footage into 4K/8K masterpieces using neural networks.",
        services: ["AI Upscaling to 4K", "Neural Frame Interpolation", "AI De-noising", "Low-Light Restoration"],
        benefits: ["Restored Legacy Content", "High-Fidelity 4K Exports", "Buttery Smooth Slow Motion", "Professional Grade Cleanup"],
        locationBlock: "Leading video restoration across India, Kerala, and UAE.",
        faqs: [{ q: "Can AI fix blurry video?", a: "Yes, our neural enhancement tools can significantly sharpen and upscale video quality." }]
    }
  },
  "ai-product-video": {
    "ai-amazon-e-comm-video-services": {
        h1: "AI Amazon & E-comm Video Services",
        cat: "AI Product Videos",
        intro: "Boost your marketplace conversion with AI-generated product videos for Amazon and Flipkart.",
        services: ["Amazon Listing Videos", "E-comm Product Explainers", "Neural Product Reels", "Buy-Box Optimization"],
        benefits: ["Higher Conversion Rates", "Compliant Ad Assets", "Rapid SKU Batching", "Professional Studio Look"],
        locationBlock: "The leading Amazon video agency in Kerala, India, and UAE.",
        faqs: [{ q: "Are AI videos allowed on Amazon?", a: "Yes, they are high-quality MP4 assets that meet all platform requirements." }]
    },
    "ai-product-demo-production-india": {
        h1: "AI Product Demo Production India",
        cat: "AI Product Videos",
        intro: "Cinematic AI-powered product demos that show, tell, and sell your brand story in the UAE and India.",
        services: ["Neural Product Walkthroughs", "3D Style AI Demos", "Feature-Highlight Videos", "Automated Demo Batching"],
        benefits: ["Perfect Educational Flow", "Cinematic Lighting", "Zero Physical Set Costs", "Global Product Appeal"],
        locationBlock: "Producing elite product demos in Kochi, Trivandrum, and the UAE.",
        faqs: [{ q: "Can AI demo software too?", a: "Yes, we specialize in both physical product and SaaS software demos." }]
    },
    "ai-shopify-visuals-production-uae": {
        h1: "AI Shopify Visuals Production UAE",
        cat: "AI Product Videos",
        intro: "Transform your Shopify store with high-conversion AI product video assets in the UAE and India.",
        services: ["Shopify Product Loops", "D2C Brand Reels", "Mobile-Optimized Assets", "Custom AI Environments"],
        benefits: ["Reduced Store Bounce Rate", "Higher Add-to-Cart", "Premium Visual Branding", "Faster Site Loading"],
        locationBlock: "Scaling Shopify brands across India, Kerala, and the UAE.",
        faqs: [{ q: "How do videos help Shopify stores?", a: "Videos increase store engagement by up to 80% compared to static images." }]
    }
  },
  "ai-explainer": {
    "ai-saas-explainer-company-india": {
        h1: "AI SaaS Explainer Company India",
        cat: "AI Explainer Videos",
        intro: "Scale your software adoption with AI-generated SaaS explainer videos in India and UAE.",
        services: ["SaaS Feature Demos", "Neural UI/UX Explainers", "Automated App Updates", "Software Storytelling"],
        benefits: ["Faster User Onboarding", "Clear Value Prop Delivery", "Scalable Multi-Language support", "Technical Accuracy"],
        locationBlock: "Leading SaaS explainers from Trivandrum/Kochi to the UAE.",
        faqs: [{ q: "Can AI explain complex features?", a: "Yes, we simplify complex SaaS logic into easy-to-digest AI visual narratives." }]
    },
    "ai-avatar-educational-videos-uae": {
        h1: "AI Avatar Educational Videos UAE",
        cat: "AI Explainer Videos",
        intro: "Humanize your educational content with photorealistic AI avatars in the UAE and India.",
        services: ["Neural Spokespersons", "Educational AI Avatars", "Multilingual Presenters", "Automated Training Hosts"],
        benefits: ["No Camera Shyness", "Instant Multilingual Sync", "24/7 Availability", "Professional Presentation"],
        locationBlock: "Pioneering AI avatars in Kerala, India, and the UAE.",
        faqs: [{ q: "Are AI avatars realistic?", a: "Yes, our latest models are indistinguishable from real human presenters." }]
    },
    "digital-ai-walkthroughs-india": {
        h1: "Digital AI Walkthroughs India",
        cat: "AI Explainer Videos",
        intro: "Engaging step-by-step digital walkthroughs for apps and services using neural animation.",
        services: ["App Process Walkthroughs", "Service Overviews", "Neural Step-by-Steps", "Interactive Video Paths"],
        benefits: ["Reduced Support Tickets", "Higher User Retention", "Clear Feature Education", "Faster Adoption"],
        locationBlock: "Dominating digital walkthroughs in Kochi/Trivandrum and UAE.",
        faqs: [{ q: "Can these be updated easily?", a: "Yes, AI allows for rapid updates if your app UI changes." }]
    }
  },
  "ai-corporate-video": {
    "ai-company-profiles-production": {
        h1: "AI Company Profiles Production",
        cat: "AI Corporate",
        intro: "Professional AI-driven company profiles that define your corporate legacy in India and UAE.",
        services: ["Neural Brand Stories", "History & Heritage AI Films", "Global Vision Videos", "Corporate Recaps"],
        benefits: ["Consistent Global Image", "Zero Site Logistics", "Cinema-Grade Branding", "Rapid Heritage Updates"],
        locationBlock: "Defining corporate profiles in Kerala, India, and the UAE.",
        faqs: [{ q: "Can AI show our factory/office?", a: "Yes, we can use existing footage and enhance it or generate photorealistic recreations." }]
    },
    "ai-internal-comms-production-india": {
        h1: "AI Internal Comms Production India",
        cat: "AI Corporate",
        intro: "Engage your workforce with AI-driven internal communications and CEO updates in India and UAE.",
        services: ["AI Townhall Summaries", "Internal Policy Videos", "CEO Announcement Films", "Training Recaps"],
        benefits: ["Higher Staff Engagement", "Rapid Messaging Pacing", "Consistent Executive Image", "Clear Vision Alignment"],
        locationBlock: "Serving the largest corporates in India and UAE from Kochi/Trivandrum.",
        faqs: [{ q: "Is AI good for internal training?", a: "Extremely. It makes training more engaging and easier to consume than text manuals." }]
    },
    "ai-employer-branding-videos-kerala": {
        h1: "AI Employer Branding Videos Kerala",
        cat: "AI Corporate",
        intro: "Attract top talent with AI-generated recruitment and employer branding films in Kerala and UAE.",
        services: ["Neural Recruitment Ads", "Work-Culture AI Films", "Employee Spotlight AI", "HR Policy Explainers"],
        benefits: ["Better Talent Attraction", "Higher Quality Applicants", "Modern Brand Image", "Strategic HR Storytelling"],
        locationBlock: "The leading employer branding agency in Kochi, Trivandrum, and UAE.",
        faqs: [{ q: "Can AI help with hiring?", a: "Yes, high-quality culture videos significantly increase applicant interest." }]
    }
  },
  "ai-video-strategy": {
    "ai-campaign-strategy-services-india": {
        h1: "AI Campaign Strategy Services India",
        cat: "AI Video Strategy",
        intro: "Data-backed video campaign strategy for high-stakes brand launches in India and UAE.",
        services: ["Total Campaign Planning", "Neural Market Research", "Campaign Asset Mapping", "Video Distribution Plans"],
        benefits: ["Guaranteed Market Impact", "Lower Ad Waste", "Data-Validated Creative", "Strategic Omnichannel Flow"],
        locationBlock: "Leading campaigns across India, Kerala, and UAE.",
        faqs: [{ q: "How do you strategize with AI?", a: "We use AI to analyze current market sentiment and competitor creative gaps." }]
    },
    "ai-video-funnel-planning-uae": {
        h1: "AI Video Funnel Planning UAE",
        cat: "AI Video Strategy",
        intro: "Optimize your sales cycle with high-conversion AI video funnels in the UAE and India.",
        services: ["TOFU/MOFU/BOFU Planning", "Retargeting AI Creative", "Customer Path Mapping", "Neural Hook Retention"],
        benefits: ["Reduced Sales Cycle", "Higher Lifetime Value", "Consistent Trust Building", "Data-Driven ROI"],
        locationBlock: "Mapping funnels in Kochi, Trivandrum, and the UAE.",
        faqs: [{ q: "Do video funnels work for B2B?", a: "Especially for B2B. They build trust and educate complex buyers at scale." }]
    },
    "ai-distribution-lab-india": {
        h1: "AI Distribution Lab India",
        cat: "AI Video Strategy",
        intro: "Master video distribution across all social and search platforms using neural optimization in India.",
        services: ["Omnichannel AI Syncing", "Search-Engine Video Optimization", "Viral Distribution Loops", "Placement Analytics"],
        benefits: ["Maximized Organic Indexing", "Perfect Platform Fit", "Higher Search Visibility", "Rapid Reach Scaling"],
        locationBlock: "Global distribution from our Kerala and UAE labs.",
        faqs: [{ q: "Where should I distribute AI videos?", a: "Everywhere. From YouTube to LinkedIn, AI allows you to adapt the content for each." }]
    }
  },
  "ai-cinematic": {
    "high-end-ai-storytelling-agency": {
        h1: "High-end AI Storytelling Agency",
        cat: "Cinematic AI",
        intro: "Elite AI-driven narrative storytelling for visionary brands in India and UAE.",
        services: ["Cinematic Narrative Loops", "Director-Level AI Flow", "Atmospheric Storytelling", "Epic Brand Narratives"],
        benefits: ["Unmatched Emotional Impact", "World-Class Visual Tone", "Strategic Brand Prestige", "Global Narrative Reach"],
        locationBlock: "Telling epic stories across Kerala, India, and UAE.",
        faqs: [{ q: "Can AI feel emotional?", a: "When guided by our directors, AI visuals and pacing evoke deep brand resonance." }]
    },
    "premium-ai-brand-films-india": {
        h1: "Premium AI Brand Films India",
        cat: "Cinematic AI",
        intro: "Defining the next generation of luxury brand films using cinema-grade AI in India and UAE.",
        services: ["Luxury AI Masterpieces", "Cinematic Brand Identity", "High-Fidelity Visuals", "Elite Brand Mastery"],
        benefits: ["Ultra-High Brand Value", "Competitive Visual Edge", "Cinema-Quality Polish", "Strategic Market Presence"],
        locationBlock: "Crafting luxury films in Kochi/Trivandrum and UAE.",
        faqs: [{ q: "How do AI brand films differ from ads?", a: "Brand films focus on legacy and identity, while ads focus on immediate conversion." }]
    }
  },
  "ai-film-narrative": {
    "ai-short-film-production-kerala": {
        h1: "AI Short Film Production Kerala",
        cat: "AI Film & Narrative",
        intro: "Scaling creative filmmaking with AI-led short film production in India and UAE.",
        services: ["Intro Short Films", "Narrative AI Prototypes", "Cinematic Story Shorts", "Festival-Grade AI Clips"],
        benefits: ["Unlimited Visual Scope", "Reduced Film Budget", "Rapid Story Iteration", "Indie Film Scaling"],
        locationBlock: "Filmmaking in the heart of Kerala, India, and the UAE.",
        faqs: [{ q: "Can AI make a whole short film?", a: "Yes, from script to screen, we use AI to handle the heavy lifting of visual creation." }]
    },
    "ai-music-video-production-india": {
        h1: "AI Music Video Production India",
        cat: "AI Film & Narrative",
        intro: "Abstract and cinematic AI music videos for artists across India and UAE.",
        services: ["Abstract AI Music Art", "Lyrical Video AI", "Cinematic Artist Profiles", "Neural Performance Sync"],
        benefits: ["Dream-Like Visuals", "Artist Branding Boost", "Zero Shoot Logistics", "Fast Content Turnaround"],
        locationBlock: "Creating music art in Kochi, Trivandrum, and UAE.",
        faqs: [{ q: "Are AI music videos trending?", a: "Yes, they are highly popular on YouTube and social media for their unique looks." }]
    },
    "ai-narrative-systems-uae": {
        h1: "AI Narrative Systems UAE",
        cat: "AI Film & Narrative",
        intro: "Building the future of interactive and systematic storytelling using AI in the UAE and India.",
        services: ["AI Narrative Logic", "Interactive Brand Stories", "Procedural Storytelling", "Neural World Building"],
        benefits: ["Deep Audience Immersion", "Scaleable Story Universes", "Future-Proof Branding", "High Retention Content"],
        locationBlock: "Building story worlds in India, Kerala, and the UAE.",
        faqs: [{ q: "What is an AI narrative system?", a: "It is a set of tools and workflows that allow for a brand's story to grow and adapt over time." }]
    }
  }
};
