export const GEO_TAXONOMY = [
  "Global",
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "New Zealand",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Philippines",
  "Vietnam",
  "Japan",
  "South Korea",
  "China",
  "Hong Kong",
  "Taiwan",
  "UAE",
  "Dubai",
  "Abu Dhabi",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Switzerland",
  "Belgium",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Brazil",
  "Mexico",
  "Kerala",
  "Tamil Nadu",
  "Karnataka",
  "Telangana",
  "Andhra Pradesh",
  "Maharashtra",
  "Delhi",
  "Gujarat",
  "Punjab",
  "West Bengal",
  "Rajasthan",
  "Kochi",
  "Trivandrum",
  "Calicut",
  "Chennai",
  "Bangalore",
  "Hyderabad",
  "Mumbai",
  "Pune",
  "Gurgaon",
  "Noida",
  "Ahmedabad"
];

export const INDUSTRY_TAXONOMY = [
  "Advertising",
  "Television Commercials",
  "AI Commercial Production",
  "Brand Films",
  "Corporate Films",
  "Product Launches",
  "Automotive",
  "Luxury Automotive",
  "Real Estate",
  "Luxury Real Estate",
  "Hospitality",
  "Hotels & Resorts",
  "Tourism",
  "Healthcare",
  "Medical",
  "Pharmaceutical",
  "Beauty",
  "Cosmetics",
  "Fashion",
  "Luxury Fashion",
  "Jewellery",
  "Watches",
  "Retail",
  "Ecommerce",
  "FMCG",
  "Food & Beverage",
  "Restaurants",
  "Consumer Electronics",
  "Technology",
  "Artificial Intelligence",
  "SaaS",
  "Cybersecurity",
  "FinTech",
  "Banking",
  "Insurance",
  "Education",
  "EdTech",
  "Government",
  "Public Sector",
  "NGO",
  "Manufacturing",
  "Industrial",
  "Construction",
  "Infrastructure",
  "Logistics",
  "Aviation",
  "Marine",
  "Energy",
  "Renewable Energy",
  "Sports",
  "Fitness",
  "Entertainment",
  "Music",
  "Film",
  "Streaming",
  "Gaming",
  "Events",
  "Wedding Industry",
  "Influencer Marketing",
  "Creator Economy",
  "Personal Branding"
];
